spring:
  application:
    name: ausolan-telegram-bot
gasca:
  base-url: https://bekosuapi.grupogasca.com/api/main
  app-secret-token: ${GASCA_APP_SECRET_TOKEN:889B640DE4E6DFB93DD9D690B5F840A9A6D89BABB4D755771053F52808F25B4A56792FDA647B6FE391745E3A461E71867A43D3A7FEE625FB2EFC9DB76C406BF9}
telegram:
  bot-token: 8883084036:AAHLNCXAgfInALRZ4ztMxqeUNewQxHOBKmc
  chat-token: "@amassorrainmenudev"
